# Generated by Django 4.1.7 on 2023-12-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='picss')),
                ('desc', models.TextField()),
            ],
        ),
    ]
